name: Deploy Azure Function (.NET 8 Isolated)

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Invoicegeni.Functions/Invoicegeni.Functions.csproj

    - name: Build project
      run: dotnet build ./Invoicegeni.Functions/Invoicegeni.Functions.csproj --configuration Release

    - name: Publish project
      run: dotnet publish ./Invoicegeni.Functions/Invoicegeni.Functions.csproj --configuration Release --output ./publish

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: invoicegeni-functions  # Your Azure Function App name
        package: ./publish
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
